import { l10n } from 'vscode';

/**
 * The user-visible text of the two bundled webview scripts. A webview script runs sandboxed in the
 * page and cannot reach the l10n API, so the panels look every string up here and inline the result
 * into the page ahead of the script. Each string is keyed by its English source the same way the
 * l10n bundle is, so a page whose host inlines no bundle still shows the English words.
 */

/**
 * The text the part grid editor page shows.
 *
 * @returns every string the page looks up, keyed by its English source.
 */
export const partGridEditorStrings = (): Record<string, string> => ({
    'View': l10n.t('View'),
    '↶ Undo': l10n.t('↶ Undo'),
    'Undo the last grid edit (Ctrl+Z)': l10n.t('Undo the last grid edit (Ctrl+Z)'),
    '↷ Redo': l10n.t('↷ Redo'),
    'Redo the last undone grid edit (Ctrl+Y)': l10n.t('Redo the last undone grid edit (Ctrl+Y)'),
    'Rotate view counter-clockwise': l10n.t('Rotate view counter-clockwise'),
    'Rotate view clockwise': l10n.t('Rotate view clockwise'),
    'Flip view horizontally': l10n.t('Flip view horizontally'),
    'Flip view vertically': l10n.t('Flip view vertically'),
    'Zoom out': l10n.t('Zoom out'),
    'Zoom in': l10n.t('Zoom in'),
    'rotation {0}°{1} (view only, coordinates stay rotation-0)': l10n.t('rotation {0}°{1} (view only, coordinates stay rotation-0)'),
    'Size': l10n.t('Size'),
    'W−': l10n.t('W−'),
    'Shrink width': l10n.t('Shrink width'),
    'W+': l10n.t('W+'),
    'Grow width': l10n.t('Grow width'),
    'H−': l10n.t('H−'),
    'Shrink height': l10n.t('Shrink height'),
    'H+': l10n.t('H+'),
    'Grow height': l10n.t('Grow height'),
    'Resizing does not move existing cell entries.': l10n.t('Resizing does not move existing cell entries.'),
    'Sprites': l10n.t('Sprites'),
    '{0} (missing)': l10n.t('{0} (missing)'),
    'No sprites resolved.': l10n.t('No sprites resolved.'),
    'Layers': l10n.t('Layers'),
    'Edit this layer': l10n.t('Edit this layer'),
    'Show this layer': l10n.t('Show this layer'),
    'inherited': l10n.t('inherited'),
    'Defined on a base part. Editing creates a local override.': l10n.t('Defined on a base part. Editing creates a local override.'),
    'Go to source': l10n.t('Go to source'),
    'Each strip is a door opening in the wall toward that cell. A dashed cell is not adjacent to the physical rect and never matches a door.': l10n.t('Each strip is a door opening in the wall toward that cell. A dashed cell is not adjacent to the physical rect and never matches a door.'),
    'Cells inside the part.': l10n.t('Cells inside the part.'),
    'Click a cell to toggle it. {0}': l10n.t('Click a cell to toggle it. {0}'),
    'Click near a cell edge/corner to toggle that wall. Right-click clears the cell.': l10n.t('Click near a cell edge/corner to toggle that wall. Right-click clears the cell.'),
    'Select a cell, then toggle directions below. Right-click clears the cell.': l10n.t('Select a cell, then toggle directions below. Right-click clears the cell.'),
    'Whole-part fallback: {0}': l10n.t('Whole-part fallback: {0}'),
    'Cell [{0}, {1}]': l10n.t('Cell [{0}, {1}]'),
    'Set {0}': l10n.t('Set {0}'),
    'Clear': l10n.t('Clear'),
    'Remove this cell entry': l10n.t('Remove this cell entry'),
    'Drag a point to move it. This list has a fixed length.': l10n.t('Drag a point to move it. This list has a fixed length.'),
    'Click to place a point, drag to move it, right-click to remove.': l10n.t('Click to place a point, drag to move it, right-click to remove.'),
    'Click the external cell, then the internal cell. Right-click a pair to remove it.': l10n.t('Click the external cell, then the internal cell. Right-click a pair to remove it.'),
    'Drag the corner handles to resize.': l10n.t('Drag the corner handles to resize.'),
    '{0} is hidden. Tick its checkbox to edit it.': l10n.t('{0} is hidden. Tick its checkbox to edit it.'),
    'Fit the part in the panel': l10n.t('Fit the part in the panel'),
    'This rect is a reference or expression, edit it in the text.': l10n.t('This rect is a reference or expression, edit it in the text.'),
    'Create': l10n.t('Create'),
    'Create the rect covering the part': l10n.t('Create the rect covering the part'),
    'Remove': l10n.t('Remove'),
    'Remove the local rect field': l10n.t('Remove the local rect field'),
    'Click to place the point, drag to move, right-click to remove.': l10n.t('Click to place the point, drag to move, right-click to remove.'),
    'Click a cell to set it, right-click to remove the field.': l10n.t('Click a cell to set it, right-click to remove the field.'),
    'Click a cell to move it. Click an edge of the current cell (or a button) to face it.': l10n.t('Click a cell to move it. Click an edge of the current cell (or a button) to face it.'),
    'Face {0}': l10n.t('Face {0}'),
    'Set': l10n.t('Set'),
    'Write MaxTiles': l10n.t('Write MaxTiles'),
    'MaxTiles: a positive integer': l10n.t('MaxTiles: a positive integer'),
    'Drag a vertex to move it. Click an edge to insert a vertex there, elsewhere to append one. Right-click removes a vertex.': l10n.t('Drag a vertex to move it. Click an edge to insert a vertex there, elsewhere to append one. Right-click removes a vertex.'),
    'This vertex is a reference or expression, edit it in the text.': l10n.t('This vertex is a reference or expression, edit it in the text.'),
    'Click to place the center, drag the ring handle to change the radius.': l10n.t('Click to place the center, drag the ring handle to change the radius.'),
    'Drag the ring handle to change the radius. The center follows the component location.': l10n.t('Drag the ring handle to change the radius. The center follows the component location.'),
    'The center follows the component. Move it in the Component locations layer.': l10n.t('The center follows the component. Move it in the Component locations layer.'),
    'Drag the halo boundary to change how many cells the region reaches beyond the part. Right-click clears the distance.': l10n.t('Drag the halo boundary to change how many cells the region reaches beyond the part. Right-click clears the distance.'),
    'Distance:': l10n.t('Distance:'),
    'Write the region distance': l10n.t('Write the region distance'),
    'Distance: a non-negative integer': l10n.t('Distance: a non-negative integer'),
    'Drag a corner handle to resize a rect, right-click one to remove it.': l10n.t('Drag a corner handle to resize a rect, right-click one to remove it.'),
    'category (e.g. tall)': l10n.t('category (e.g. tall)'),
    'Add rect': l10n.t('Add rect'),
    'Append a rect above the part': l10n.t('Append a rect above the part'),
    'Scalar fields also prohibit: {0} (dashed).': l10n.t('Scalar fields also prohibit: {0} (dashed).'),
    'Click a marker to select (clicking a stack cycles through it), drag to move. Grey markers are chained or reference-valued.': l10n.t('Click a marker to select (clicking a stack cycles through it), drag to move. Grey markers are chained or reference-valued.'),
    '{0} components (click to cycle)': l10n.t('{0} components (click to cycle)'),
    'no location': l10n.t('no location'),
    'ref': l10n.t('ref'),
    'Chained to {0}. Dragging edits its local offset.': l10n.t('Chained to {0}. Dragging edits its local offset.'),
    'The location is a reference or expression, edit it in the text.': l10n.t('The location is a reference or expression, edit it in the text.'),
    'Rotation:': l10n.t('Rotation:'),
    'Write the rotation in degrees': l10n.t('Write the rotation in degrees'),
    'Rotation: a number in degrees': l10n.t('Rotation: a number in degrees'),
    'Rotate to {0} degrees': l10n.t('Rotate to {0} degrees'),
    'Snap:': l10n.t('Snap:'),
    'free': l10n.t('free'),
    'Snap to {0} cells': l10n.t('Snap to {0} cells'),
    'Rotation & flipping': l10n.t('Rotation & flipping'),
    'e.g. 0, 2, 1, 3': l10n.t('e.g. 0, 2, 1, 3'),
    'Write {0}': l10n.t('Write {0}'),
    '{0}: only integers': l10n.t('{0}: only integers'),
    'Use the view rotation above to preview how rotations will look.': l10n.t('Use the view rotation above to preview how rotations will look.'),
    'Toggling writes the field.': l10n.t('Toggling writes the field.'),
    'Unset, the game defaults to Sides.': l10n.t('Unset, the game defaults to Sides.'),
    'Unset': l10n.t('Unset'),
    'Remove the local field': l10n.t('Remove the local field'),
    'Virtual cell: now click the internal cell (right-click cancels)': l10n.t('Virtual cell: now click the internal cell (right-click cancels)'),
    'cell [{0}]  ·  [{1}]': l10n.t('cell [{0}]  ·  [{1}]'),
    'No part found at this position.': l10n.t('No part found at this position.'),
    'Edit rejected ({0}). Resyncing…': l10n.t('Edit rejected ({0}). Resyncing…'),
});

/**
 * The text the shader preview page shows.
 *
 * @returns every string the page looks up, keyed by its English source.
 */
export const shaderPreviewStrings = (): Record<string, string> => ({
    'Vertex color (anim)': l10n.t('Vertex color (anim)'),
    'Vertex color': l10n.t('Vertex color'),
    'The particle system animates this colour over each particle’s lifetime (ColorRamp). Uncheck anim to hold a colour.': l10n.t('The particle system animates this colour over each particle’s lifetime (ColorRamp). Uncheck anim to hold a colour.'),
    'A particle drives its effect with per-vertex colour. Red sweeps the animation, alpha is brightness.': l10n.t('A particle drives its effect with per-vertex colour. Red sweeps the animation, alpha is brightness.'),
    'The material vertex-colour tint.': l10n.t('The material vertex-colour tint.'),
    'anim': l10n.t('anim'),
    'Beam': l10n.t('Beam'),
    'The per-vertex beam inputs: intensity scales the effect, fade multiplies alpha over the beam’s life.': l10n.t('The per-vertex beam inputs: intensity scales the effect, fade multiplies alpha over the beam’s life.'),
    'Sprite cell': l10n.t('Sprite cell'),
    'The particle system picks one cell of the sprite sheet (UvSprites). Cycle replays the animation over the lifetime.': l10n.t('The particle system picks one cell of the sprite sheet (UvSprites). Cycle replays the animation over the lifetime.'),
    'cycle': l10n.t('cycle'),
    '{0} (default {1})': l10n.t('{0} (default {1})'),
    'Replay the engine clock driving this constant. Uncheck to set it manually.': l10n.t('Replay the engine clock driving this constant. Uncheck to set it manually.'),
    'auto': l10n.t('auto'),
    'Preview backdrop': l10n.t('Preview backdrop'),
    'Checker': l10n.t('Checker'),
    'Dark': l10n.t('Dark'),
    'Light': l10n.t('Light'),
    'Grey': l10n.t('Grey'),
    'Backdrop': l10n.t('Backdrop'),
    'Blend mode (the material’s resolved mode, overridable)': l10n.t('Blend mode (the material’s resolved mode, overridable)'),
    'material': l10n.t('material'),
    'Blend': l10n.t('Blend'),
    'Pause': l10n.t('Pause'),
    'Play': l10n.t('Play'),
    'shader compile failed': l10n.t('shader compile failed'),
    'shader compile failed: {0}': l10n.t('shader compile failed: {0}'),
    'shader not translatable': l10n.t('shader not translatable'),
    'Approximate render ({0}). Texture, tint and blend shown.': l10n.t('Approximate render ({0}). Texture, tint and blend shown.'),
    'Live translated shader.': l10n.t('Live translated shader.'),
    'vertex stage ({0})': l10n.t('vertex stage ({0})'),
    'particle: color ramp animated': l10n.t('particle: color ramp animated'),
    'particle: vertex colour animated': l10n.t('particle: vertex colour animated'),
    'beam': l10n.t('beam'),
    'sprite sheet: {0} cells': l10n.t('sprite sheet: {0} cells'),
    'scene stand-in': l10n.t('scene stand-in'),
    'WebGL1 fallback': l10n.t('WebGL1 fallback'),
    'Open .shader': l10n.t('Open .shader'),
    'Place the cursor in a material with a Shader to preview it.': l10n.t('Place the cursor in a material with a Shader to preview it.'),
    'WebGL is not available in this webview.': l10n.t('WebGL is not available in this webview.'),
});
