import { l10n } from 'vscode';

/**
 * The user-visible text of the bundled webview pages. A webview script runs sandboxed in the page
 * and cannot reach the l10n API, so the panels write the loaded bundle into the page ahead of the
 * script and the page looks its strings up in it. Every string is keyed by its English source the
 * same way the bundle is, so a page whose host loaded none, which is what running in English
 * means, falls back to the key and still shows the English words.
 *
 * @returns the loaded translations, keyed by their English source, empty when none are loaded.
 */
export const webviewStrings = (): Record<string, string> => l10n.bundle ?? {};

/**
 * The text the bundled pages show. Nothing reads this list: the pages are handed the whole bundle
 * above. It stands here because `npm run l10n` builds that bundle by scanning the source for
 * `l10n.t` calls, and the pages themselves live under `media/`, which the scan does not read.
 *
 * @returns the strings, only so that the scan finds them.
 */
export const webviewPageText = (): string[] => [
    l10n.t('View'),
    l10n.t('↶ Undo'),
    l10n.t('Undo the last grid edit (Ctrl+Z)'),
    l10n.t('↷ Redo'),
    l10n.t('Redo the last undone grid edit (Ctrl+Y)'),
    l10n.t('Rotate view counter-clockwise'),
    l10n.t('Rotate view clockwise'),
    l10n.t('Flip view horizontally'),
    l10n.t('Flip view vertically'),
    l10n.t('Zoom out'),
    l10n.t('Zoom in'),
    l10n.t('rotation {0}°{1} (view only, coordinates stay rotation-0)'),
    l10n.t('Size'),
    l10n.t('W−'),
    l10n.t('Shrink width'),
    l10n.t('W+'),
    l10n.t('Grow width'),
    l10n.t('H−'),
    l10n.t('Shrink height'),
    l10n.t('H+'),
    l10n.t('Grow height'),
    l10n.t('Resizing does not move existing cell entries.'),
    l10n.t('Sprites'),
    l10n.t('{0} (missing)'),
    l10n.t('No sprites resolved.'),
    l10n.t('Layers'),
    l10n.t('Edit this layer'),
    l10n.t('Show this layer'),
    l10n.t('inherited'),
    l10n.t('Defined on a base part. Editing creates a local override.'),
    l10n.t('Go to source'),
    l10n.t(
        'Each strip is a door opening in the wall toward that cell. A dashed cell is not adjacent to the physical rect and never matches a door.'
    ),
    l10n.t('Cells inside the part.'),
    l10n.t('Click a cell to toggle it. {0}'),
    l10n.t('Click near a cell edge/corner to toggle that wall. Right-click clears the cell.'),
    l10n.t('Select a cell, then toggle directions below. Right-click clears the cell.'),
    l10n.t('Whole-part fallback: {0}'),
    l10n.t('Cell [{0}, {1}]'),
    l10n.t('Set {0}'),
    l10n.t('Clear'),
    l10n.t('Remove this cell entry'),
    l10n.t('Drag a point to move it. This list has a fixed length.'),
    l10n.t('Click to place a point, drag to move it, right-click to remove.'),
    l10n.t('Click the external cell, then the internal cell. Right-click a pair to remove it.'),
    l10n.t('Drag the corner handles to resize.'),
    l10n.t('{0} is hidden. Tick its checkbox to edit it.'),
    l10n.t('Fit the part in the panel'),
    l10n.t(
        'Drag the corner handles to resize. This rect is written from references, so the numbers are written where they are declared.'
    ),
    l10n.t('Create'),
    l10n.t('Create the rect covering the part'),
    l10n.t('Remove'),
    l10n.t('Remove the local rect field'),
    l10n.t('Click to place the point, drag to move, right-click to remove.'),
    l10n.t('Click a cell to set it, right-click to remove the field.'),
    l10n.t('Click a cell to move it. Click an edge of the current cell (or a button) to face it.'),
    l10n.t('Face {0}'),
    l10n.t('Set'),
    l10n.t('Write MaxTiles'),
    l10n.t('MaxTiles: a positive integer'),
    l10n.t(
        'Drag a vertex to move it. Click an edge to insert a vertex there, elsewhere to append one. Right-click removes a vertex.'
    ),
    l10n.t('Click to place the center, drag the ring handle to change the radius.'),
    l10n.t('Drag the ring handle to change the radius. The center follows the component location.'),
    l10n.t('The center follows the component. Move it in the Component locations layer.'),
    l10n.t(
        'Drag the halo boundary to change how many cells the region reaches beyond the part. Right-click clears the distance.'
    ),
    l10n.t('Distance:'),
    l10n.t('Write the region distance'),
    l10n.t('Distance: a non-negative integer'),
    l10n.t('Drag a corner handle to resize a rect, right-click one to remove it.'),
    l10n.t('category (e.g. tall)'),
    l10n.t('Add rect'),
    l10n.t('Append a rect above the part'),
    l10n.t('Scalar fields also prohibit: {0} (dashed).'),
    l10n.t(
        'Click a marker to select (clicking a stack cycles through it), drag to move. Grey markers are chained or reference-valued.'
    ),
    l10n.t('{0} components (click to cycle)'),
    l10n.t('no location'),
    l10n.t('ref'),
    l10n.t('Chained to {0}. Dragging edits its local offset.'),
    l10n.t('This location is written from references, so the numbers are written where they are declared.'),
    l10n.t('Rotation:'),
    l10n.t('Write the rotation in degrees'),
    l10n.t('Rotation: a number in degrees'),
    l10n.t('Rotate to {0} degrees'),
    l10n.t('Snap:'),
    l10n.t('free'),
    l10n.t('Snap to {0} cells'),
    l10n.t('Rotation & flipping'),
    l10n.t('e.g. 0, 2, 1, 3'),
    l10n.t('Write {0}'),
    l10n.t('{0}: only integers'),
    l10n.t('Use the view rotation above to preview how rotations will look.'),
    l10n.t('Toggling writes the field.'),
    l10n.t('Unset, the game defaults to Sides.'),
    l10n.t('Unset'),
    l10n.t('Remove the local field'),
    l10n.t('Virtual cell: now click the internal cell (right-click cancels)'),
    l10n.t('cell [{0}]  ·  [{1}]'),
    l10n.t('No part found at this position.'),
    l10n.t('This part could not be drawn. Reopen the editor to try again.'),
    l10n.t('Edit rejected ({0}). Resyncing…'),
    l10n.t('Vertex color (anim)'),
    l10n.t('Vertex color'),
    l10n.t(
        'The particle system animates this colour over each particle’s lifetime (ColorRamp). Uncheck anim to hold a colour.'
    ),
    l10n.t('A particle drives its effect with per-vertex colour. Red sweeps the animation, alpha is brightness.'),
    l10n.t('The material vertex-colour tint.'),
    l10n.t('anim'),
    l10n.t('Beam'),
    l10n.t('The per-vertex beam inputs: intensity scales the effect, fade multiplies alpha over the beam’s life.'),
    l10n.t('Sprite cell'),
    l10n.t(
        'The particle system picks one cell of the sprite sheet (UvSprites). Cycle replays the animation over the lifetime.'
    ),
    l10n.t('cycle'),
    l10n.t('{0} (default {1})'),
    l10n.t('Replay the engine clock driving this constant. Uncheck to set it manually.'),
    l10n.t('auto'),
    l10n.t('Preview backdrop'),
    l10n.t('Checker'),
    l10n.t('Dark'),
    l10n.t('Light'),
    l10n.t('Grey'),
    l10n.t('Backdrop'),
    l10n.t('Blend mode (the material’s resolved mode, overridable)'),
    l10n.t('material'),
    l10n.t('Blend'),
    l10n.t('Pause'),
    l10n.t('Play'),
    l10n.t('shader compile failed'),
    l10n.t('shader compile failed: {0}'),
    l10n.t('shader not translatable'),
    l10n.t('Approximate render ({0}). Texture, tint and blend shown.'),
    l10n.t('Live translated shader.'),
    l10n.t('vertex stage ({0})'),
    l10n.t('particle: color ramp animated'),
    l10n.t('particle: vertex colour animated'),
    l10n.t('beam'),
    l10n.t('sprite sheet: {0} cells'),
    l10n.t('scene stand-in'),
    l10n.t('WebGL1 fallback'),
    l10n.t('Open .shader'),
    l10n.t('Place the cursor in a material with a Shader to preview it.'),
    l10n.t('WebGL is not available in this webview.'),
    l10n.t('Fit the whole diagram into the panel'),
    l10n.t('Filter boxes'),
    l10n.t('Nothing to draw here.'),
    l10n.t('Filter parts'),
    l10n.t('1 typed value belongs to a part this table is not showing, and was left alone.'),
    l10n.t('{0} typed values belong to parts this table is not showing, and were left alone.'),
    l10n.t('The parts could not be read.'),
    l10n.t('Search columns'),
    l10n.t('Column name'),
    l10n.t('[MaxHealth] / [@Tiles]'),
    l10n.t('Following your edit…'),
    l10n.t('No group'),
    l10n.t('No grouping'),
    l10n.t('By build menu group'),
    l10n.t('By ship class, then build menu group'),
    l10n.t('By ship class'),
    l10n.t('No ship class'),
    l10n.t('No category'),
    l10n.t('No mod'),
    l10n.t('Ship class'),
    l10n.t('Category'),
    l10n.t('Mod'),
    l10n.t('All parts'),
    l10n.t('The game and {0}'),
    l10n.t('The game alone. Open a file of your mod to add it.'),
    l10n.t('Show tree'),
    l10n.t('Hide tree'),
    l10n.t('By category'),
    l10n.t('By mod'),
    l10n.t('Group'),
    l10n.t('Show these parts'),
    l10n.t('Hide these parts'),
    l10n.t('Average'),
    l10n.t('Least'),
    l10n.t('Most'),
    l10n.t('Every number is per tile.'),
    l10n.t('computed'),
    l10n.t('Formula: {0}'),
    l10n.t('Write 1 change to the files'),
    l10n.t('Write {0} changes to the files'),
    l10n.t('Discard typed values'),
    l10n.t('Write a number, with the % d or r suffix the value already has.'),
    l10n.t('Typed over {0}. Write the changes to put it in the file.'),
    l10n.t('Typed over. Write the changes to put it in the file.'),
    l10n.t('Inherited. Click to open the declaration, double-click to try a value.'),
    l10n.t('Click to open the declaration, double-click to try a value.'),
    l10n.t('Credits paid for every point of health'),
    l10n.t('Damage per second for every credit'),
    l10n.t('Damage per shot times fire rate, times the barrels where a part counts them'),
    l10n.t('Steel and coils added up, for the parts that take only one of them too'),
    l10n.t('Every resource the part takes, added up'),
    l10n.t('Percent of the average of the parts on screen'),
    l10n.t('Rank by health, 1 for the highest'),
    l10n.t('Reading the parts…'),
    l10n.t('Reading the picked columns…'),
    l10n.t('Narrowing to the parts you picked…'),
    l10n.t('Putting the view back…'),
    l10n.t('No view saved yet.'),
    l10n.t('Insert a column on screen:'),
    l10n.t('No column is on screen to insert.'),
    l10n.t('Delete'),
    l10n.t('{0} of {1} columns shown'),
    l10n.t('Freeze this column at the left edge'),
    l10n.t('Drag to set the width, double-click to let the column size itself'),
    l10n.t('Unfreeze this column'),
    l10n.t('Every number is shown as its percentage of the compared part, so 200% is twice as much.'),
    l10n.t('Pick a part to compare against first.'),
    l10n.t(
        'Blue is below the compared part, grey within half a percent of it, red above it. The deeper shade is past twice or under half. The colour says where the number stands, not whether that is better.'
    ),
    l10n.t('Health for every cell the part takes up'),
    l10n.t('Rounded to one decimal'),
    l10n.t('Percent of the compared part'),
    l10n.t('1 for the parts above ten thousand health, 0 for the rest'),
    l10n.t('The larger of two columns'),
    l10n.t('Part'),
    l10n.t('From'),
    l10n.t('Component'),
    l10n.t('Every category'),
    l10n.t('Every component'),
    l10n.t('Everywhere'),
    l10n.t('Compare with nothing'),
    l10n.t('No parts found.'),
    l10n.t('No part is left in the part of the tree you picked.'),
    l10n.t('No part matches the filter.'),
    l10n.t('No column matches.'),
    l10n.t('Click to open the declaration.'),
    l10n.t('Inherited. Click to open the declaration.'),
    l10n.t('{0} of {1} parts'),
    l10n.t('{0} parts'),
    l10n.t('The project holds more parts than the table reads.'),
];
