<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>rules</string>
    <key>scopeName</key>
    <string>source.rules</string>
    <key>fileTypes</key>
    <array>
      <string>rules</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#functions</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#expression</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#paren-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;=:|=) ?(true|false)</string>
            <key>name</key>
            <string>constant.language</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric</string>
            <key>match</key>
            <string>\-?.?\d+\.?\d*</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric</string>
            <key>match</key>
            <string>\d+\.\d*E\+\d+</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.name</string>
            <key>match</key>
            <string>[a-zA-Z_][a-zA-Z0-9_]+ ?(?=:|=|)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.tag</string>
            <key>match</key>
            <string>[&amp;|&lt;|^|/|..][&lt;&gt;~./\w_]+</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.quoted</string>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>constant.character.escape</string>
                <key>match</key>
                <string>\\.</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>string.unquoted</string>
            <key>match</key>
            <string>((?&lt;= = )[^0-9.\[\-&amp;&lt;\^\(\)][\w._]+[ ]?[\w]*)(?!=|:|\()</string>
          </dict>
        </array>
      </dict>
      <key>functions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>support.function</string>
            <key>match</key>
            <string>(?&lt;=:|=) ?[a-zA-Z_][a-zA-Z0-9_]+ ?(?=\()</string>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.parameter</string>
            <key>begin</key>
            <string>\(</string>
            <key>end</key>
            <string>\)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.paren.open</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.paren.close</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>constant.numeric</string>
                <key>match</key>
                <string>\b(\-?\d+.?\d*)\b</string>
              </dict>
              <dict>
                <key>name</key>
                <string>variable.parameter</string>
                <key>match</key>
                <string> ?[a-zA-Z_][a-zA-Z0-9_]+ ?(?=,)</string>
              </dict>
              <dict>
                <key>name</key>
                <string>entity.name.tag</string>
                <key>match</key>
                <string>[&amp;|&lt;|^][&lt;&gt;.\/\w_]+</string>
              </dict>
              <dict>
                <key>name</key>
                <string>punctuation.comma</string>
                <key>match</key>
                <string>,</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.block</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>//</string>
            <key>end</key>
            <string>$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.line.double-slash</string>
          </dict>
        </array>
        <key>name</key>
        <string>comment</string>
      </dict>
      <key>paren-expression</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>end</key>
        <string>\)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.paren.open</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.paren.close</string>
          </dict>
        </dict>
        <key>name</key>
        <string>expression.group</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>