#!/usr/bin/env node
/**
 * Field-documentation tool. Turns the machine-extracted schema into a community-editable Markdown
 * tree and compiles that tree back into the `field-docs.json` the language server ships.
 *
 * Three subcommands:
 *   scaffold  schema.json + field-docs.seed.json → docs/fields/<Type>.md
 *             Idempotent. Regenerates the machine-owned skeleton (H1, per-field `##` heading, the
 *             type-signature line) while preserving every word of human prose. New fields get a TODO
 *             placeholder, pre-filled from the XML seed when available. Fields dropped from the schema
 *             are moved to a "Removed fields" section (prose kept, never silently deleted).
 *   compile   docs/fields/*.md → server/src/document/schema/field-docs.json
 *             The shipped artifact the server imports. Only prose for fields that still exist in the
 *             schema is emitted; TODO placeholders and removed fields are skipped.
 *   lint      Validate the docs tree against the schema and report coverage. Exit 1 on any problem
 *             (heading for an unknown field, file for an unknown type, stale field-docs.json).
 *
 * The editable source of truth is docs/fields/*.md. See docs/fields/README.md for the contributor
 * workflow. Run with: `node tools/docsgen/docsgen.mjs <scaffold|compile|lint>`.
 */
import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..');
const SCHEMA_PATH = join(REPO, 'server', 'src', 'document', 'schema', 'cosmoteer.schema.json');
const SEED_PATH = join(REPO, 'server', 'src', 'document', 'schema', 'field-docs.seed.json');
// Curated, committed prose transcribed from the Cosmoteer modding wiki (cosmoteer.wiki.gg). Takes
// precedence over the auto-extracted XML seed because it is written for modders. Fields only. The
// wiki remains the place for guides and worked examples.
const WIKI_SEED_PATH = join(HERE, 'wiki-seed.json');
const DOCS_DIR = join(REPO, 'docs', 'fields');
const OUT_JSON = join(REPO, 'server', 'src', 'document', 'schema', 'field-docs.json');

const TODO = '<!-- TODO: needs documentation -->';
const OUTDATED = '<!-- OUTDATED: not in the current schema. Prose kept so it is not lost — delete if truly gone. -->';
const PREAMBLE =
    '> Machine-generated skeleton. Write prose under each `## Field` heading; the heading and the\n' +
    "> type-signature line below it are regenerated by the scaffolder — don't hand-edit them. Add\n" +
    '> `[[links]]` and Markdown freely in the prose. See [README](./README.md) to contribute.\n' +
    '>\n' +
    '> These docs describe individual fields. For guides, worked examples and the bigger picture, see\n' +
    '> the [Cosmoteer modding wiki](https://cosmoteer.wiki.gg/wiki/Modding).';

const readJson = (p) => JSON.parse(readFileSync(p, 'utf8'));

/** A short human label for a field value type. Mirrors valueTypeLabel in schema.ts (cosmetic only). */
const label = (vt) => {
    switch (vt.kind) {
        case 'enum': return `enum ${vt.name}`;
        case 'reference': return `→ ${vt.targetName}`;
        case 'group':
        case 'polymorphicGroup': return vt.name;
        case 'list': return `${label(vt.element)}[]`;
        case 'range': return `range<${label(vt.element)}>`;
        case 'interpolated': return `interpolated<${label(vt.element)}>`;
        case 'map': return `map<${label(vt.key)}, ${label(vt.value)}>`;
        case 'tuple': return `[${vt.elements.map(label).join(', ')}]`;
        case 'asset': return `asset (${vt.assetKind})`;
        case 'code': return `code (${vt.lang})`;
        case 'constructed':
        case 'generic': return vt.type;
        case 'number': return vt.unit ? `number (${vt.unit})` : 'number';
        case 'opaque': return vt.reason === 'typeParam' ? 'any' : vt.type;
        default: return vt.kind;
    }
};

/** The regenerated, machine-owned type-signature line shown under a field heading. */
const signatureLine = (field, enums) => {
    const parts = [`\`${label(field.valueType)}\``];
    parts.push(field.optional ? 'optional' : 'required');
    if (field.default !== undefined) parts.push(`default \`${field.default}\``);
    const vt = field.valueType;
    if (vt.kind === 'enum') {
        const members = enums[vt.ref]?.members ?? [];
        if (members.length > 0 && members.length <= 12) parts.push(`one of: ${members.map((m) => `\`${m}\``).join(', ')}`);
    }
    return parts.join(' · ');
};

/** A schema type FullName turned into a safe flat filename (dots kept; nested `/` and generic backtick escaped). */
const fileNameFor = (fullName) => `${fullName.replace(/\//g, '+').replace(/`/g, '-')}.md`;

/**
 * Parse a docs Markdown file into its canonical type (from the H1) and a field→prose map. The first
 * non-empty line under each `## Field` heading is the regenerated signature line and is discarded; the
 * remainder is the human prose. This is the single reader used by scaffold, compile and lint, so all
 * three agree on where the machine skeleton ends and the human content begins.
 */
const parseDoc = (md) => {
    const lines = md.split(/\r?\n/);
    let type = null;
    let i = 0;
    for (; i < lines.length; i++) {
        const m = lines[i].match(/^# (.+?)\s*$/);
        if (m) { type = m[1]; i++; break; }
    }
    const fields = new Map();
    let cur = null;
    let buf = [];
    let sawSignature = false;
    const flush = () => {
        if (cur != null) fields.set(cur, buf.join('\n').trim());
        cur = null; buf = []; sawSignature = false;
    };
    for (; i < lines.length; i++) {
        const h = lines[i].match(/^## (.+?)\s*$/);
        if (h) { flush(); cur = h[1]; continue; }
        if (cur == null) continue;
        if (!sawSignature) { if (lines[i].trim() !== '') sawSignature = true; continue; }
        buf.push(lines[i]);
    }
    flush();
    return { type, fields };
};

/** Prose that counts as real documentation (not an empty body or a TODO/OUTDATED marker). */
const isDocumented = (prose) => prose && prose !== TODO && !prose.startsWith('<!-- OUTDATED');

/** Types worth a docs file: those with at least one own field to document. */
const documentableTypes = (schema) =>
    Object.entries(schema.types)
        .filter(([, t]) => (t.fields ?? []).length > 0)
        .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));

const readExistingDocs = () => {
    const byType = new Map();
    if (!existsSync(DOCS_DIR)) return byType;
    for (const name of readdirSync(DOCS_DIR)) {
        if (!name.endsWith('.md') || name === 'README.md') continue;
        const { type, fields } = parseDoc(readFileSync(join(DOCS_DIR, name), 'utf8'));
        if (type) byType.set(type, { fields, file: name });
    }
    return byType;
};

/** Merge the auto-extracted XML seed with the curated wiki seed; the wiki wins per field. */
const mergedSeed = () => {
    const xml = existsSync(SEED_PATH) ? readJson(SEED_PATH) : {};
    const wiki = existsSync(WIKI_SEED_PATH) ? readJson(WIKI_SEED_PATH) : {};
    const out = {};
    for (const src of [xml, wiki])
        for (const [type, fields] of Object.entries(src)) out[type] = { ...out[type], ...fields };
    return out;
};

const scaffold = () => {
    const schema = readJson(SCHEMA_PATH);
    const seed = mergedSeed();
    if (!existsSync(SEED_PATH)) {
        console.warn(`note: ${SEED_PATH} not found, scaffolding from the wiki seed and TODO placeholders only.\n` +
            '      Regenerate it with schemagen (needs the game DLLs) to also pre-fill from the game XML docs.');
    }
    mkdirSync(DOCS_DIR, { recursive: true });
    const existing = readExistingDocs();
    let documented = 0;
    let todo = 0;
    let outdated = 0;
    let filesWritten = 0;

    for (const [fullName, type] of documentableTypes(schema)) {
        const prior = existing.get(fullName)?.fields ?? new Map();
        const schemaNames = new Set(type.fields.map((f) => f.name));
        const out = [`# ${fullName}`, '', PREAMBLE, ''];

        for (const field of type.fields) {
            // Prefer human prose already written, then the XML seed, else a TODO placeholder.
            const priorProse = prior.get(field.name);
            let prose;
            if (isDocumented(priorProse)) prose = priorProse;
            else if (seed[fullName]?.[field.name]) prose = seed[fullName][field.name];
            else prose = TODO;
            if (prose === TODO) todo++;
            else documented++;
            out.push(`## ${field.name}`, signatureLine(field, schema.enums), '', prose, '');
        }

        // Fields that once had docs but are gone from the schema: keep their prose, flag them.
        const removed = [...prior.keys()].filter((n) => !schemaNames.has(n) && isDocumented(prior.get(n)));
        if (removed.length > 0) {
            out.push('---', '', '## Removed fields', '');
            for (const name of removed) {
                outdated++;
                out.push(`## ${name}`, OUTDATED, '', prior.get(name), '');
            }
        }

        writeFileSync(join(DOCS_DIR, fileNameFor(fullName)), out.join('\n').replace(/\n+$/, '\n'), 'utf8');
        filesWritten++;
    }

    const total = documented + todo;
    console.log(`scaffold: ${filesWritten} files · ${documented}/${total} fields documented ` +
        `(${((100 * documented) / total).toFixed(1)}%) · ${todo} TODO · ${outdated} removed-but-kept`);
};

const compile = () => {
    const schema = readJson(SCHEMA_PATH);
    const existing = readExistingDocs();
    const docs = {};
    let count = 0;
    for (const [fullName, type] of documentableTypes(schema)) {
        const prior = existing.get(fullName)?.fields;
        if (!prior) continue;
        const entry = {};
        for (const field of type.fields) {
            const prose = prior.get(field.name);
            if (isDocumented(prose)) { entry[field.name] = prose; count++; }
        }
        if (Object.keys(entry).length > 0) docs[fullName] = entry;
    }
    const ordered = {};
    for (const k of Object.keys(docs).sort()) ordered[k] = docs[k];
    writeFileSync(OUT_JSON, `${JSON.stringify(ordered, null, 4)}\n`, 'utf8');
    console.log(`compile: ${count} documented fields across ${Object.keys(ordered).length} types → ${OUT_JSON}`);
    return ordered;
};

const lint = () => {
    const schema = readJson(SCHEMA_PATH);
    const problems = [];
    const ownFields = (t) => new Set((schema.types[t]?.fields ?? []).map((f) => f.name));
    let documented = 0;
    let total = 0;
    for (const [, t] of documentableTypes(schema)) total += t.fields.length;

    if (existsSync(DOCS_DIR)) {
        for (const name of readdirSync(DOCS_DIR)) {
            if (!name.endsWith('.md') || name === 'README.md') continue;
            const { type, fields } = parseDoc(readFileSync(join(DOCS_DIR, name), 'utf8'));
            if (!type) { problems.push(`${name}: missing '# <TypeFullName>' H1`); continue; }
            if (!schema.types[type]) { problems.push(`${name}: type '${type}' is not in the schema`); continue; }
            const own = ownFields(type);
            for (const [field, prose] of fields) {
                if (!own.has(field)) {
                    if (isDocumented(prose)) problems.push(`${name}: '${field}' is not a field of ${type} (documented but unknown)`);
                    continue;
                }
                if (isDocumented(prose)) documented++;
            }
        }
    }

    // Stale check: the shipped field-docs.json must match a fresh compile of the tree.
    if (existsSync(OUT_JSON)) {
        const fresh = {};
        const existing = readExistingDocs();
        for (const [fullName, type] of documentableTypes(schema)) {
            const prior = existing.get(fullName)?.fields;
            if (!prior) continue;
            const entry = {};
            for (const field of type.fields) if (isDocumented(prior.get(field.name))) entry[field.name] = prior.get(field.name);
            if (Object.keys(entry).length > 0) fresh[fullName] = entry;
        }
        const orderedFresh = {};
        for (const k of Object.keys(fresh).sort()) orderedFresh[k] = fresh[k];
        const current = readFileSync(OUT_JSON, 'utf8').trim();
        if (`${JSON.stringify(orderedFresh, null, 4)}` !== current)
            problems.push('field-docs.json is stale — run `node tools/docsgen/docsgen.mjs compile`');
    }

    console.log(`lint: ${documented}/${total} fields documented (${((100 * documented) / total).toFixed(1)}%)`);
    if (problems.length > 0) {
        console.error(`\n${problems.length} problem(s):`);
        for (const p of problems) console.error(`  - ${p}`);
        process.exit(1);
    }
    console.log('lint: ok');
};

const cmd = process.argv[2];
if (cmd === 'scaffold') scaffold();
else if (cmd === 'compile') compile();
else if (cmd === 'lint') lint();
else {
    console.error('usage: node tools/docsgen/docsgen.mjs <scaffold|compile|lint>');
    process.exit(2);
}
